   SELECT
          TABELA2.COLIGADA
        , TABELA2.CGC
        , TABELA2.FILIAL
        , TABELA2.ENDERECOFILIAL
        , TABELA2.SECAO
        , TABELA2.DEPARTAMENTO
        , TABELA2.CPF
        , TABELA2.CHAPA
        , TABELA2.NOME
        , TABELA2.SITUACAO
        , TABELA2.FUNCAO
        , TABELA2.DATAADMISSAO
        , TABELA2.DTNASCIMENTO
        , TABELA2.GESTOR_IMEDIATO
        , TABELA2.DATADEMISSAO
        , TABELA2.TELEFONE1
        , TABELA2.IDADE
        , TABELA2.SEXO
        , TABELA2.SALARIO
        , TABELA2.RECEBIMENTO
        , TABELA2.CARGAHORARIA
        , TABELA2.EMAIL
        , TABELA2.SINDICATO
        , TABELA2.DEFICIENTEAUDITIVO
    	, TABELA2.DEFICIENTEFALA
    	, TABELA2.DEFICIENTEFISICO
    	, TABELA2.DEFICIENTEINTELECTUAL
    	, TABELA2.DEFICIENTEMENTAL
    	, TABELA2.DEFICIENTEMOBREDUZIDA
    	, TABELA2.DEFICIENTEVISUAL
    	, TABELA2.TIPO_FUNCIONARIO
        , TABELA2.PISPASEP
        , TABELA2.CARTIDENTIDADE
        , TABELA2.ORGEMISSORIDENT
        , TABELA2.NROCTPS
        , TABELA2.SERIECTPS
        , TABELA2.CENTRO_DE_CUSTO
        , TABELA2.CODBANCOPAGTO
        , TABELA2.CODAGENCIAPAGTO
        , TABELA2.CONTAPAGAMENTO
        , TABELA2.OPBANCARIA
        , TABELA2.RUA
        , TABELA2.NUMERO
        , TABELA2.BAIRRO
        , TABELA2.ESTADO
        , TABELA2.CEP
        , TABELA2.ESTADOCIVIL
        , TABELA2.APOSENTADO
        , TABELA2.GRAUINSTRUCAO
        , TABELA2.NOMEMAE
        , TABELA2.NOMEPAI
        , TABELA2.MOTIVO_RESCISAO
        
        FROM

(
   SELECT 
        
        CAST(PFUNC.CODCOLIGADA AS VARCHAR(100)) || ' - ' || GCOLIGADA.NOMEFANTASIA AS COLIGADA
	  , PSECAO.CGC
	  , CAST(GFILIAL.CODFILIAL AS VARCHAR(100)) || ' - ' || GFILIAL.NOMEFANTASIA AS FILIAL
	  , GFILIAL.ESTADO || ' - ' || GFILIAL.BAIRRO || ' - ' || GFILIAL.CIDADE AS ENDERECOFILIAL
	  , PFUNC.CODSECAO || ' - ' || PSECAO.DESCRICAO AS SECAO
      , GDEPTO.NOME AS DEPARTAMENTO
	  , PPESSOA.CPF
	  , PFUNC.CHAPA
	  , PFUNC.NOME 
	  , PFUNC.CODSITUACAO || ' - ' || PCODSITUACAO.DESCRICAO AS SITUACAO
	  , CAST(PFUNC.CODFUNCAO AS VARCHAR(100)) || ' - ' || PFUNCAO.NOME AS FUNCAO
	  , PFUNC.DATAADMISSAO
	  , PPESSOA.DTNASCIMENTO
           ,coalesce(
           (SELECT P0.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C0 INNER JOIN U_ABDHDU_RM.PEXTERNO F0 ON F0.CODEXTERNO = C0.CODEXTERNO AND F0.CODCOLIGADA = C0.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P0 ON P0.CODIGO = F0.CODPESSOA WHERE C0.CODCOLIGADA = pfunc.CODCOLIGADA AND P0.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C0.DATAINICIO AND C0.DATAFIM) OR C0.DATAFIM IS NULL) AND C0.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO))AND rownum <=1),
           (SELECT F0.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C0 INNER JOIN U_ABDHDU_RM.PFUNC F0 ON F0.CHAPA = C0.CHAPASUBST AND F0.CODCOLIGADA = C0.CODCOLSUBST WHERE C0.CODCOLIGADA = pfunc.CODCOLIGADA AND C0.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C0.DATAINICIO AND C0.DATAFIM) OR C0.DATAFIM IS NULL) AND C0.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO))AND rownum <=1),
           (SELECT P1.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C1 INNER JOIN U_ABDHDU_RM.PEXTERNO F1 ON F1.CODEXTERNO = C1.CODEXTERNO AND F1.CODCOLIGADA = C1.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P1 ON P1.CODIGO = F1.CODPESSOA WHERE C1.CODCOLIGADA = pfunc.CODCOLIGADA AND P1.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C1.DATAINICIO AND C1.DATAFIM) OR C1.DATAFIM IS NULL) AND C1.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 3)AND rownum <=1),
           (SELECT F1.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C1 INNER JOIN U_ABDHDU_RM.PFUNC F1 ON F1.CHAPA = C1.CHAPASUBST AND F1.CODCOLIGADA = C1.CODCOLSUBST WHERE C1.CODCOLIGADA = pfunc.CODCOLIGADA AND C1.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C1.DATAINICIO AND C1.DATAFIM) OR C1.DATAFIM IS NULL) AND C1.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 3)AND rownum <=1),
           (SELECT P2.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C2 INNER JOIN U_ABDHDU_RM.PEXTERNO F2 ON F2.CODEXTERNO = C2.CODEXTERNO AND F2.CODCOLIGADA = C2.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P2 ON P2.CODIGO = F2.CODPESSOA WHERE C2.CODCOLIGADA = pfunc.CODCOLIGADA AND P2.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C2.DATAINICIO AND C2.DATAFIM) OR C2.DATAFIM IS NULL) AND C2.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 6)AND rownum <=1),
           (SELECT F2.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C2 INNER JOIN U_ABDHDU_RM.PFUNC F2 ON F2.CHAPA = C2.CHAPASUBST AND F2.CODCOLIGADA = C2.CODCOLSUBST WHERE C2.CODCOLIGADA = pfunc.CODCOLIGADA AND C2.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C2.DATAINICIO AND C2.DATAFIM) OR C2.DATAFIM IS NULL) AND C2.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 6)AND rownum <=1),
           (SELECT P3.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C3 INNER JOIN U_ABDHDU_RM.PEXTERNO F3 ON F3.CODEXTERNO = C3.CODEXTERNO AND F3.CODCOLIGADA = C3.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P3 ON P3.CODIGO = F3.CODPESSOA WHERE C3.CODCOLIGADA = pfunc.CODCOLIGADA AND P3.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C3.DATAINICIO AND C3.DATAFIM) OR C3.DATAFIM IS NULL) AND C3.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 9)AND rownum <=1),
           (SELECT F3.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C3 INNER JOIN U_ABDHDU_RM.PFUNC F3 ON F3.CHAPA = C3.CHAPASUBST AND F3.CODCOLIGADA = C3.CODCOLSUBST WHERE C3.CODCOLIGADA = pfunc.CODCOLIGADA AND C3.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C3.DATAINICIO AND C3.DATAFIM) OR C3.DATAFIM IS NULL) AND C3.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 9)AND rownum <=1),
           (SELECT P4.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C4 INNER JOIN U_ABDHDU_RM.PEXTERNO F4 ON F4.CODEXTERNO = C4.CODEXTERNO AND F4.CODCOLIGADA = C4.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P4 ON P4.CODIGO = F4.CODPESSOA WHERE C4.CODCOLIGADA = pfunc.CODCOLIGADA AND P4.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C4.DATAINICIO AND C4.DATAFIM) OR C4.DATAFIM IS NULL) AND C4.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 12)AND rownum <=1),
           (SELECT F4.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C4 INNER JOIN U_ABDHDU_RM.PFUNC F4 ON F4.CHAPA = C4.CHAPASUBST AND F4.CODCOLIGADA = C4.CODCOLSUBST WHERE C4.CODCOLIGADA = pfunc.CODCOLIGADA AND C4.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C4.DATAINICIO AND C4.DATAFIM) OR C4.DATAFIM IS NULL) AND C4.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 12)AND rownum <=1),
           (SELECT P5.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C5 INNER JOIN U_ABDHDU_RM.PEXTERNO F5 ON F5.CODEXTERNO = C5.CODEXTERNO AND F5.CODCOLIGADA = C5.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P5 ON P5.CODIGO = F5.CODPESSOA WHERE C5.CODCOLIGADA = pfunc.CODCOLIGADA AND P5.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C5.DATAINICIO AND C5.DATAFIM) OR C5.DATAFIM IS NULL) AND C5.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 15)AND rownum <=1),
           (SELECT F5.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C5 INNER JOIN U_ABDHDU_RM.PFUNC F5 ON F5.CHAPA = C5.CHAPASUBST AND F5.CODCOLIGADA = C5.CODCOLSUBST WHERE C5.CODCOLIGADA = pfunc.CODCOLIGADA AND C5.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C5.DATAINICIO AND C5.DATAFIM) OR C5.DATAFIM IS NULL) AND C5.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 15)AND rownum <=1),
           (SELECT P6.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C6 INNER JOIN U_ABDHDU_RM.PEXTERNO F6 ON F6.CODEXTERNO = C6.CODEXTERNO AND F6.CODCOLIGADA = C6.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P6 ON P6.CODIGO = F6.CODPESSOA WHERE C6.CODCOLIGADA = pfunc.CODCOLIGADA AND P6.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C6.DATAINICIO AND C6.DATAFIM) OR C6.DATAFIM IS NULL) AND C6.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 18)AND rownum <=1),
           (SELECT F6.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C6 INNER JOIN U_ABDHDU_RM.PFUNC F6 ON F6.CHAPA = C6.CHAPASUBST AND F6.CODCOLIGADA = C6.CODCOLSUBST WHERE C6.CODCOLIGADA = pfunc.CODCOLIGADA AND C6.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C6.DATAINICIO AND C6.DATAFIM) OR C6.DATAFIM IS NULL) AND C6.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 18)AND rownum <=1),
           (SELECT P7.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C7 INNER JOIN U_ABDHDU_RM.PEXTERNO F7 ON F7.CODEXTERNO = C7.CODEXTERNO AND F7.CODCOLIGADA = C7.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P7 ON P7.CODIGO = F7.CODPESSOA WHERE C7.CODCOLIGADA = pfunc.CODCOLIGADA AND P7.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C7.DATAINICIO AND C7.DATAFIM) OR C7.DATAFIM IS NULL) AND C7.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 21)AND rownum <=1),
           (SELECT F7.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C7 INNER JOIN U_ABDHDU_RM.PFUNC F7 ON F7.CHAPA = C7.CHAPASUBST AND F7.CODCOLIGADA = C7.CODCOLSUBST WHERE C7.CODCOLIGADA = pfunc.CODCOLIGADA AND C7.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C7.DATAINICIO AND C7.DATAFIM) OR C7.DATAFIM IS NULL) AND C7.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 21)AND rownum <=1),
           (SELECT P8.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C8 INNER JOIN U_ABDHDU_RM.PEXTERNO F8 ON F8.CODEXTERNO = C8.CODEXTERNO AND F8.CODCOLIGADA = C8.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P8 ON P8.CODIGO = F8.CODPESSOA WHERE C8.CODCOLIGADA = pfunc.CODCOLIGADA AND P8.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C8.DATAINICIO AND C8.DATAFIM) OR C8.DATAFIM IS NULL) AND C8.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 24)AND rownum <=1),
           (SELECT F8.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C8 INNER JOIN U_ABDHDU_RM.PFUNC F8 ON F8.CHAPA = C8.CHAPASUBST AND F8.CODCOLIGADA = C8.CODCOLSUBST WHERE C8.CODCOLIGADA = pfunc.CODCOLIGADA AND C8.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C8.DATAINICIO AND C8.DATAFIM) OR C8.DATAFIM IS NULL) AND C8.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 24)AND rownum <=1),
           'NAO-DEFINIDO') 	AS GESTOR_IMEDIATO
	  , PFUNC.DATADEMISSAO
      , (SELECT NOMEDOPAI.NOME FROM  U_ABDHDU_RM.PFDEPEND NOMEDOPAI WHERE NOMEDOPAI.CODCOLIGADA = PFUNC.CODCOLIGADA AND NOMEDOPAI.CHAPA = PFUNC.CHAPA AND NOMEDOPAI.GRAUPARENTESCO = '6' AND rownum <=1)  AS NOMEPAI
      , (SELECT NOMEDAMAE.NOME  FROM U_ABDHDU_RM.PFDEPEND NOMEDAMAE WHERE NOMEDAMAE.CODCOLIGADA = PFUNC.CODCOLIGADA AND NOMEDAMAE.CHAPA = PFUNC.CHAPA AND NOMEDAMAE.GRAUPARENTESCO = '7' AND rownum <=1 ) AS NOMEMAE
	  , PPESSOA.TELEFONE1
      , TRUNC((MONTHS_BETWEEN(SYSDATE, PPESSOA.DTNASCIMENTO))/12) AS IDADE
      , CASE WHEN PPESSOA.SEXO = 'M' THEN 'Masculino' ELSE 'Feminino' END AS SEXO
	  , PFUNC.SALARIO
	  , PFUNC.CODRECEBIMENTO || ' - ' || PCODRECEB.DESCRICAO AS RECEBIMENTO
	  , CONCAT(CAST(PFUNC.JORNADAMENSAL/60 AS VARCHAR(100)),':00') AS CARGAHORARIA
	  , PPESSOA.EMAIL
	  , PFUNC.CODSINDICATO || ' - ' || PSINDIC.NOME AS SINDICATO
	  , CASE WHEN PPESSOA.DEFICIENTEFISICO      = 1 THEN 'Sim' ELSE 'Não' END DEFICIENTEFISICO
	  , CASE WHEN PPESSOA.DEFICIENTEAUDITIVO    = 2 THEN 'Sim' ELSE 'Não' END DEFICIENTEAUDITIVO
	  , CASE WHEN PPESSOA.DEFICIENTEFALA        = 3 THEN 'Sim' ELSE 'Não' END DEFICIENTEFALA
      , CASE WHEN PPESSOA.DEFICIENTEVISUAL      = 4 THEN 'Sim' ELSE 'Não' END DEFICIENTEVISUAL
	  , CASE WHEN PPESSOA.DEFICIENTEMENTAL      = 5 THEN 'Sim' ELSE 'Não' END DEFICIENTEMENTAL
	  , CASE WHEN PPESSOA.DEFICIENTEINTELECTUAL = 6 THEN 'Sim' ELSE 'Não' END DEFICIENTEINTELECTUAL
      , CASE WHEN PPESSOA.DEFICIENTEMOBREDUZIDA = 7 THEN 'Sim' ELSE 'Não' END DEFICIENTEMOBREDUZIDA
      ,	CASE PFUNC.CODTIPO
			WHEN 'A' THEN 'Autonomo'
		 	WHEN 'C' THEN 'Conselheiro'
		 	WHEN 'D' THEN 'Diretor'
		 	WHEN 'E' THEN 'Estatuario Cedido '
		 	WHEN 'I' THEN 'Cedido'
		 	WHEN 'M' THEN 'Misto'
		 	WHEN 'N' THEN 'Normal'
		 	WHEN 'O' THEN 'Comissionista'
		 	WHEN 'P' THEN 'Temporario'
		 	WHEN 'R' THEN 'Rural'
		 	WHEN 'S' THEN 'Pensionista'
		 	WHEN 'T' THEN 'Estagiario'
		 	WHEN 'X' THEN 'Expatriado'
		 	WHEN 'Z' THEN 'Aprendiz' END AS TIPO_FUNCIONARIO
	  , PFUNC.PISPASEP
	  , PPESSOA.CARTIDENTIDADE
	  , PPESSOA.ORGEMISSORIDENT
	  , PPESSOA.CARTEIRATRAB AS NROCTPS
	  , PPESSOA.SERIECARTTRAB AS SERIECTPS
	  , PMOTDEMISSAO.DESCRICAO AS MOTIVO_RESCISAO
      	 ,  CASE WHEN PFUNC.CODCOLIGADA <> 12 THEN CCUSTOCOMPL.CCSAP ELSE SUBSTR(GCCUSTO.NOME,2,10) END AS CENTRO_DE_CUSTO
     /*, CCUSTOCOMPL.CCSAP 	AS CENTRO_DE_CUSTO*/
	  , PFUNC.CODBANCOPAGTO
	  , PFUNC.CODAGENCIAPAGTO
	  , PFUNC.CONTAPAGAMENTO
	  , PFUNC.OPBANCARIA
	  , PPESSOA.RUA
	  , PPESSOA.NUMERO
	  , PPESSOA.BAIRRO
	  , PPESSOA.ESTADO
	  , PPESSOA.CEP
	  , PPESSOA.ESTADOCIVIL || ' - ' || PCODESTCIVIL.DESCRICAO AS ESTADOCIVIL
	  , CASE WHEN PFUNC.APOSENTADO = '1' THEN 'Sim' ELSE 'Não' END AS APOSENTADO
	  , PPESSOA.GRAUINSTRUCAO  || ' - ' || PCODINSTRUCAO.DESCRICAO AS GRAUINSTRUCAO
  FROM U_ABDHDU_RM.PFUNC 
       INNER JOIN U_ABDHDU_RM.GCOLIGADA ON PFUNC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
	   INNER JOIN U_ABDHDU_RM.GFILIAL ON GFILIAL.CODCOLIGADA = PFUNC.CODCOLIGADA AND GFILIAL.CODFILIAL = PFUNC.CODFILIAL
	   INNER JOIN U_ABDHDU_RM.PSECAO ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO
       INNER JOIN U_ABDHDU_RM.GDEPTO ON GDEPTO.CODCOLIGADA = PSECAO.CODCOLIGADA AND GDEPTO.CODFILIAL = GFILIAL.CODFILIAL AND GDEPTO.CODDEPARTAMENTO = PSECAO.CODDEPTO
	   INNER JOIN U_ABDHDU_RM.PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
	   INNER JOIN U_ABDHDU_RM.PCODSITUACAO  ON PCODSITUACAO.CODCLIENTE = PFUNC.CODSITUACAO
	   INNER JOIN U_ABDHDU_RM.PFUNCAO ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
	   INNER JOIN U_ABDHDU_RM.PCODRECEB ON PCODRECEB.CODCLIENTE = PFUNC.CODRECEBIMENTO
	   INNER JOIN U_ABDHDU_RM.PSINDIC  ON PSINDIC.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSINDIC.CODIGO = PFUNC.CODSINDICATO
	   INNER JOIN U_ABDHDU_RM.PCODESTCIVIL ON PCODESTCIVIL.CODCLIENTE = PPESSOA.ESTADOCIVIL
	   INNER JOIN U_ABDHDU_RM.PCODINSTRUCAO  ON PCODINSTRUCAO.CODCLIENTE = PPESSOA.GRAUINSTRUCAO
	   LEFT JOIN U_ABDHDU_RM.PMOTDEMISSAO ON (PMOTDEMISSAO.CODINTERNO = PFUNC.MOTIVODEMISSAO)
	   LEFT JOIN U_ABDHDU_RM.PFRATEIOFIXO ON (PFRATEIOFIXO.CODCOLIGADA = PFUNC.CODCOLIGADA
                                   AND  PFRATEIOFIXO.CHAPA = PFUNC.CHAPA )     
	   LEFT JOIN U_ABDHDU_RM.GCCUSTO ON (GCCUSTO.CODCOLIGADA = PFRATEIOFIXO.CODCOLIGADA
                             AND  GCCUSTO.CODCCUSTO = PFRATEIOFIXO.CODCCUSTO)
       LEFT JOIN U_ABDHDU_RM.CCUSTOCOMPL ON (CCUSTOCOMPL.CODCOLIGADA = PSECAO.CODCOLIGADA
                                         AND  CCUSTOCOMPL.CODCCUSTO  = PSECAO.nrocencustocont)
  WHERE PFUNC.CODCOLIGADA LIKE COALESCE(:PLN_$B$1_S,'%')
    AND PFUNC.CODSITUACAO <> 'D'

  UNION 
   

 SELECT 
        CAST(PFUNC.CODCOLIGADA AS VARCHAR(100)) || ' - ' || GCOLIGADA.NOMEFANTASIA AS COLIGADA
	  , PSECAO.CGC
	  , CAST(GFILIAL.CODFILIAL AS VARCHAR(100)) || ' - ' || GFILIAL.NOMEFANTASIA AS FILIAL
	  , GFILIAL.ESTADO || ' - ' || GFILIAL.BAIRRO || ' - ' || GFILIAL.CIDADE AS ENDERECOFILIAL
	  , PFUNC.CODSECAO || ' - ' || PSECAO.DESCRICAO AS SECAO
      , GDEPTO.NOME AS DEPARTAMENTO
	  , PPESSOA.CPF
	  , PFUNC.CHAPA
	  , PFUNC.NOME 
	  , PFUNC.CODSITUACAO || ' - ' || PCODSITUACAO.DESCRICAO AS SITUACAO
	  , CAST(PFUNC.CODFUNCAO AS VARCHAR(100)) || ' - ' || PFUNCAO.NOME AS FUNCAO
	  , PFUNC.DATAADMISSAO
	  , PPESSOA.DTNASCIMENTO
           ,coalesce(
           (SELECT P0.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C0 INNER JOIN U_ABDHDU_RM.PEXTERNO F0 ON F0.CODEXTERNO = C0.CODEXTERNO AND F0.CODCOLIGADA = C0.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P0 ON P0.CODIGO = F0.CODPESSOA WHERE C0.CODCOLIGADA = pfunc.CODCOLIGADA AND P0.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C0.DATAINICIO AND C0.DATAFIM) OR C0.DATAFIM IS NULL) AND C0.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO))AND rownum <=1),
           (SELECT F0.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C0 INNER JOIN U_ABDHDU_RM.PFUNC F0 ON F0.CHAPA = C0.CHAPASUBST AND F0.CODCOLIGADA = C0.CODCOLSUBST WHERE C0.CODCOLIGADA = pfunc.CODCOLIGADA AND C0.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C0.DATAINICIO AND C0.DATAFIM) OR C0.DATAFIM IS NULL) AND C0.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO))AND rownum <=1),
           (SELECT P1.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C1 INNER JOIN U_ABDHDU_RM.PEXTERNO F1 ON F1.CODEXTERNO = C1.CODEXTERNO AND F1.CODCOLIGADA = C1.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P1 ON P1.CODIGO = F1.CODPESSOA WHERE C1.CODCOLIGADA = pfunc.CODCOLIGADA AND P1.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C1.DATAINICIO AND C1.DATAFIM) OR C1.DATAFIM IS NULL) AND C1.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 3)AND rownum <=1),
           (SELECT F1.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C1 INNER JOIN U_ABDHDU_RM.PFUNC F1 ON F1.CHAPA = C1.CHAPASUBST AND F1.CODCOLIGADA = C1.CODCOLSUBST WHERE C1.CODCOLIGADA = pfunc.CODCOLIGADA AND C1.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C1.DATAINICIO AND C1.DATAFIM) OR C1.DATAFIM IS NULL) AND C1.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 3)AND rownum <=1),
           (SELECT P2.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C2 INNER JOIN U_ABDHDU_RM.PEXTERNO F2 ON F2.CODEXTERNO = C2.CODEXTERNO AND F2.CODCOLIGADA = C2.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P2 ON P2.CODIGO = F2.CODPESSOA WHERE C2.CODCOLIGADA = pfunc.CODCOLIGADA AND P2.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C2.DATAINICIO AND C2.DATAFIM) OR C2.DATAFIM IS NULL) AND C2.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 6)AND rownum <=1),
           (SELECT F2.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C2 INNER JOIN U_ABDHDU_RM.PFUNC F2 ON F2.CHAPA = C2.CHAPASUBST AND F2.CODCOLIGADA = C2.CODCOLSUBST WHERE C2.CODCOLIGADA = pfunc.CODCOLIGADA AND C2.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C2.DATAINICIO AND C2.DATAFIM) OR C2.DATAFIM IS NULL) AND C2.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 6)AND rownum <=1),
           (SELECT P3.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C3 INNER JOIN U_ABDHDU_RM.PEXTERNO F3 ON F3.CODEXTERNO = C3.CODEXTERNO AND F3.CODCOLIGADA = C3.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P3 ON P3.CODIGO = F3.CODPESSOA WHERE C3.CODCOLIGADA = pfunc.CODCOLIGADA AND P3.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C3.DATAINICIO AND C3.DATAFIM) OR C3.DATAFIM IS NULL) AND C3.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 9)AND rownum <=1),
           (SELECT F3.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C3 INNER JOIN U_ABDHDU_RM.PFUNC F3 ON F3.CHAPA = C3.CHAPASUBST AND F3.CODCOLIGADA = C3.CODCOLSUBST WHERE C3.CODCOLIGADA = pfunc.CODCOLIGADA AND C3.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C3.DATAINICIO AND C3.DATAFIM) OR C3.DATAFIM IS NULL) AND C3.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 9)AND rownum <=1),
           (SELECT P4.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C4 INNER JOIN U_ABDHDU_RM.PEXTERNO F4 ON F4.CODEXTERNO = C4.CODEXTERNO AND F4.CODCOLIGADA = C4.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P4 ON P4.CODIGO = F4.CODPESSOA WHERE C4.CODCOLIGADA = pfunc.CODCOLIGADA AND P4.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C4.DATAINICIO AND C4.DATAFIM) OR C4.DATAFIM IS NULL) AND C4.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 12)AND rownum <=1),
           (SELECT F4.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C4 INNER JOIN U_ABDHDU_RM.PFUNC F4 ON F4.CHAPA = C4.CHAPASUBST AND F4.CODCOLIGADA = C4.CODCOLSUBST WHERE C4.CODCOLIGADA = pfunc.CODCOLIGADA AND C4.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C4.DATAINICIO AND C4.DATAFIM) OR C4.DATAFIM IS NULL) AND C4.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 12)AND rownum <=1),
           (SELECT P5.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C5 INNER JOIN U_ABDHDU_RM.PEXTERNO F5 ON F5.CODEXTERNO = C5.CODEXTERNO AND F5.CODCOLIGADA = C5.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P5 ON P5.CODIGO = F5.CODPESSOA WHERE C5.CODCOLIGADA = pfunc.CODCOLIGADA AND P5.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C5.DATAINICIO AND C5.DATAFIM) OR C5.DATAFIM IS NULL) AND C5.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 15)AND rownum <=1),
           (SELECT F5.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C5 INNER JOIN U_ABDHDU_RM.PFUNC F5 ON F5.CHAPA = C5.CHAPASUBST AND F5.CODCOLIGADA = C5.CODCOLSUBST WHERE C5.CODCOLIGADA = pfunc.CODCOLIGADA AND C5.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C5.DATAINICIO AND C5.DATAFIM) OR C5.DATAFIM IS NULL) AND C5.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 15)AND rownum <=1),
           (SELECT P6.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C6 INNER JOIN U_ABDHDU_RM.PEXTERNO F6 ON F6.CODEXTERNO = C6.CODEXTERNO AND F6.CODCOLIGADA = C6.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P6 ON P6.CODIGO = F6.CODPESSOA WHERE C6.CODCOLIGADA = pfunc.CODCOLIGADA AND P6.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C6.DATAINICIO AND C6.DATAFIM) OR C6.DATAFIM IS NULL) AND C6.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 18)AND rownum <=1),
           (SELECT F6.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C6 INNER JOIN U_ABDHDU_RM.PFUNC F6 ON F6.CHAPA = C6.CHAPASUBST AND F6.CODCOLIGADA = C6.CODCOLSUBST WHERE C6.CODCOLIGADA = pfunc.CODCOLIGADA AND C6.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C6.DATAINICIO AND C6.DATAFIM) OR C6.DATAFIM IS NULL) AND C6.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 18)AND rownum <=1),
           (SELECT P7.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C7 INNER JOIN U_ABDHDU_RM.PEXTERNO F7 ON F7.CODEXTERNO = C7.CODEXTERNO AND F7.CODCOLIGADA = C7.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P7 ON P7.CODIGO = F7.CODPESSOA WHERE C7.CODCOLIGADA = pfunc.CODCOLIGADA AND P7.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C7.DATAINICIO AND C7.DATAFIM) OR C7.DATAFIM IS NULL) AND C7.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 21)AND rownum <=1),
           (SELECT F7.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C7 INNER JOIN U_ABDHDU_RM.PFUNC F7 ON F7.CHAPA = C7.CHAPASUBST AND F7.CODCOLIGADA = C7.CODCOLSUBST WHERE C7.CODCOLIGADA = pfunc.CODCOLIGADA AND C7.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C7.DATAINICIO AND C7.DATAFIM) OR C7.DATAFIM IS NULL) AND C7.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 21)AND rownum <=1),
           (SELECT P8.NOME FROM U_ABDHDU_RM.PCHEFEEXTERNO C8 INNER JOIN U_ABDHDU_RM.PEXTERNO F8 ON F8.CODEXTERNO = C8.CODEXTERNO AND F8.CODCOLIGADA = C8.CODCOLIGADA INNER JOIN U_ABDHDU_RM.PPESSOA P8 ON P8.CODIGO = F8.CODPESSOA WHERE C8.CODCOLIGADA = pfunc.CODCOLIGADA AND P8.CODIGO <> PPESSOA.CODIGO AND ((SYSDATE BETWEEN C8.DATAINICIO AND C8.DATAFIM) OR C8.DATAFIM IS NULL) AND C8.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 24)AND rownum <=1),
           (SELECT F8.NOME FROM U_ABDHDU_RM.PSUBSTCHEFE C8 INNER JOIN U_ABDHDU_RM.PFUNC F8 ON F8.CHAPA = C8.CHAPASUBST AND F8.CODCOLIGADA = C8.CODCOLSUBST WHERE C8.CODCOLIGADA = pfunc.CODCOLIGADA AND C8.CHAPASUBST <> PFUNC.CHAPA AND ((SYSDATE BETWEEN C8.DATAINICIO AND C8.DATAFIM) OR C8.DATAFIM IS NULL) AND C8.CODSECAO = substr(pfunc.CODSECAO, 1, LENGTH(pfunc.CODSECAO) - 24)AND rownum <=1),
           'NAO-DEFINIDO') 	AS GESTOR_IMEDIATO
	  , PFUNC.DATADEMISSAO
	  , (SELECT NOMEDOPAI.NOME FROM  U_ABDHDU_RM.PFDEPEND NOMEDOPAI WHERE NOMEDOPAI.CODCOLIGADA = PFUNC.CODCOLIGADA AND NOMEDOPAI.CHAPA = PFUNC.CHAPA AND NOMEDOPAI.GRAUPARENTESCO = '6' AND rownum <=1)  AS NOMEPAI
      , (SELECT NOMEDAMAE.NOME  FROM U_ABDHDU_RM.PFDEPEND NOMEDAMAE WHERE NOMEDAMAE.CODCOLIGADA = PFUNC.CODCOLIGADA AND NOMEDAMAE.CHAPA = PFUNC.CHAPA AND NOMEDAMAE.GRAUPARENTESCO = '7' AND rownum <=1 ) AS NOMEMAE
	  , PPESSOA.TELEFONE1
      , TRUNC((MONTHS_BETWEEN(SYSDATE, PPESSOA.DTNASCIMENTO))/12) AS IDADE
      , CASE WHEN PPESSOA.SEXO = 'M' THEN 'Masculino' ELSE 'Feminino' END AS SEXO
	  , PFUNC.SALARIO
	  , PFUNC.CODRECEBIMENTO || ' - ' || PCODRECEB.DESCRICAO AS RECEBIMENTO
	  , CONCAT(CAST(PFUNC.JORNADAMENSAL/60 AS VARCHAR(100)),':00') AS CARGAHORARIA
	  , PPESSOA.EMAIL
	  , PFUNC.CODSINDICATO || ' - ' || PSINDIC.NOME AS SINDICATO
      , CASE WHEN PPESSOA.DEFICIENTEFISICO      = 1 THEN 'Sim' ELSE 'Não' END DEFICIENTEFISICO
	  , CASE WHEN PPESSOA.DEFICIENTEAUDITIVO    = 2 THEN 'Sim' ELSE 'Não' END DEFICIENTEAUDITIVO
	  , CASE WHEN PPESSOA.DEFICIENTEFALA        = 3 THEN 'Sim' ELSE 'Não' END DEFICIENTEFALA
      , CASE WHEN PPESSOA.DEFICIENTEVISUAL      = 4 THEN 'Sim' ELSE 'Não' END DEFICIENTEVISUAL
	  , CASE WHEN PPESSOA.DEFICIENTEMENTAL      = 5 THEN 'Sim' ELSE 'Não' END DEFICIENTEMENTAL
	  , CASE WHEN PPESSOA.DEFICIENTEINTELECTUAL = 6 THEN 'Sim' ELSE 'Não' END DEFICIENTEINTELECTUAL
      , CASE WHEN PPESSOA.DEFICIENTEMOBREDUZIDA = 7 THEN 'Sim' ELSE 'Não' END DEFICIENTEMOBREDUZIDA
	  ,	CASE PFUNC.CODTIPO
			WHEN 'A' THEN 'Autonomo'
		 	WHEN 'C' THEN 'Conselheiro'
		 	WHEN 'D' THEN 'Diretor'
		 	WHEN 'E' THEN 'Estatuario Cedido '
		 	WHEN 'I' THEN 'Cedido'
		 	WHEN 'M' THEN 'Misto'
		 	WHEN 'N' THEN 'Normal'
		 	WHEN 'O' THEN 'Comissionista'
		 	WHEN 'P' THEN 'Temporario'
		 	WHEN 'R' THEN 'Rural'
		 	WHEN 'S' THEN 'Pensionista'
		 	WHEN 'T' THEN 'Estagiario'
		 	WHEN 'X' THEN 'Expatriado'
		 	WHEN 'Z' THEN 'Aprendiz' END AS TIPO_FUNCIONARIO
	  , PFUNC.PISPASEP
	  , PPESSOA.CARTIDENTIDADE
	  , PPESSOA.ORGEMISSORIDENT
	  , PPESSOA.CARTEIRATRAB AS NROCTPS
	  , PPESSOA.SERIECARTTRAB AS SERIECTPS
	  , PMOTDEMISSAO.DESCRICAO AS MOTIVO_RESCISAO
      	 ,  CASE WHEN PFUNC.CODCOLIGADA <> 12 THEN CCUSTOCOMPL.CCSAP ELSE SUBSTR(GCCUSTO.NOME,2,10) END AS CENTRO_DE_CUSTO
  	/* , CCUSTOCOMPL.CCSAP 	AS CENTRO_DE_CUSTO*/
	  , PFUNC.CODBANCOPAGTO
	  , PFUNC.CODAGENCIAPAGTO
	  , PFUNC.CONTAPAGAMENTO
	  , PFUNC.OPBANCARIA
	  , PPESSOA.RUA
	  , PPESSOA.NUMERO
	  , PPESSOA.BAIRRO
	  , PPESSOA.ESTADO
	  , PPESSOA.CEP
	  , PPESSOA.ESTADOCIVIL || ' - ' || PCODESTCIVIL.DESCRICAO AS ESTADOCIVIL
	  , CASE WHEN PFUNC.APOSENTADO = '1' THEN 'Sim' ELSE 'Não' END AS APOSENTADO
	  , PPESSOA.GRAUINSTRUCAO  || ' - ' || PCODINSTRUCAO.DESCRICAO AS GRAUINSTRUCAO
  FROM U_ABDHDU_RM.PFUNC 
       INNER JOIN U_ABDHDU_RM.GCOLIGADA ON PFUNC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
	   INNER JOIN U_ABDHDU_RM.GFILIAL ON GFILIAL.CODCOLIGADA = PFUNC.CODCOLIGADA AND GFILIAL.CODFILIAL = PFUNC.CODFILIAL
	   INNER JOIN U_ABDHDU_RM.PSECAO ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO
       INNER JOIN U_ABDHDU_RM.GDEPTO ON GDEPTO.CODCOLIGADA = PSECAO.CODCOLIGADA AND GDEPTO.CODFILIAL = GFILIAL.CODFILIAL AND GDEPTO.CODDEPARTAMENTO = PSECAO.CODDEPTO
	   INNER JOIN U_ABDHDU_RM.PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
	   INNER JOIN U_ABDHDU_RM.PCODSITUACAO  ON PCODSITUACAO.CODCLIENTE = PFUNC.CODSITUACAO
	   INNER JOIN U_ABDHDU_RM.PFUNCAO ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
	   INNER JOIN U_ABDHDU_RM.PCODRECEB ON PCODRECEB.CODCLIENTE = PFUNC.CODRECEBIMENTO
	   INNER JOIN U_ABDHDU_RM.PSINDIC  ON PSINDIC.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSINDIC.CODIGO = PFUNC.CODSINDICATO
	   INNER JOIN U_ABDHDU_RM.PCODESTCIVIL ON PCODESTCIVIL.CODCLIENTE = PPESSOA.ESTADOCIVIL
	   INNER JOIN U_ABDHDU_RM.PCODINSTRUCAO  ON PCODINSTRUCAO.CODCLIENTE = PPESSOA.GRAUINSTRUCAO
       LEFT JOIN U_ABDHDU_RM.PMOTDEMISSAO ON (PMOTDEMISSAO.CODINTERNO = PFUNC.MOTIVODEMISSAO)
	   LEFT JOIN U_ABDHDU_RM.PFRATEIOFIXO ON (PFRATEIOFIXO.CODCOLIGADA = PFUNC.CODCOLIGADA
                                   AND  PFRATEIOFIXO.CHAPA = PFUNC.CHAPA )     
	   LEFT JOIN U_ABDHDU_RM.GCCUSTO ON (GCCUSTO.CODCOLIGADA = PFRATEIOFIXO.CODCOLIGADA
                             AND  GCCUSTO.CODCCUSTO = PFRATEIOFIXO.CODCCUSTO)
       LEFT JOIN U_ABDHDU_RM.CCUSTOCOMPL ON (CCUSTOCOMPL.CODCOLIGADA = PSECAO.CODCOLIGADA
                                         AND  CCUSTOCOMPL.CODCCUSTO  = PSECAO.nrocencustocont)
  WHERE PFUNC.CODCOLIGADA LIKE COALESCE(:PLN_$B$1_S,'%')
    AND PFUNC.DATADEMISSAO BETWEEN :PLN_$B$2_D AND :PLN_$B$3_D
    
 )TABELA2   
    
ORDER BY 1, 3, 8
